"""
This type stub file was partly generated by cyright.
"""

from enum import IntEnum, StrEnum
from typing import Any, Callable

from fsticker.async_feed import *
from fsticker.feed_merge import *  # type: ignore

class FeedType(IntEnum):
    Touchline = 0
    SnapQuote = 1

class AccessType(StrEnum):
    API = "API"
    WEB = "WEB"
    MOB = "MOB"

class TableMode(StrEnum):
    SINGLE = "single"
    TIMEFRAME = "per_timeframe"

class LogLevel(IntEnum):
    DEBUG = 0
    INFO = 1
    WARN = 2
    ERROR = 3

class Credentials:
    def __init__(
        self,
        name: str,
        ws_endpoint: str,
        user_id: str,
        token: str,
        access_type: AccessType = AccessType.API,
        verify_ssl: bool = False,
        enable_ip_pinning: bool = False,
        idle_ping_timeout: float = 3.0,
        ping_reply_timeout: float = 2.0,
        ping_payload: str = '{"t":"h"}',
        min_log_level: LogLevel = LogLevel.INFO,
    ) -> None: ...

class TimescaleConfig:
    def __init__(
        self,
        host: str,
        dbname: str,
        user: str,
        password: str,
        port: int = 5432,
        table: str = "candles",
        table_mode: TableMode = TableMode.TIMEFRAME,
        connect_timeout: float = 5.0,
        auto_bootstrap_schema: bool = True,
    ) -> None: ...

class MergedFeed:
    @property
    def on_tick(self) -> Callable[[Any], Any] | None: ...
    @on_tick.setter
    def on_tick(self, cb: Callable[[Any], Any] | None) -> None: ...
    @property
    def on_candle(self) -> Callable[[Any], Any] | None: ...
    @on_candle.setter
    def on_candle(self, cb: Callable[[Any], Any] | None) -> None: ...
    @property
    def on_order(self) -> Callable[[str, Any], Any] | None: ...
    @on_order.setter
    def on_order(self, cb: Callable[[str, Any], Any] | None) -> None: ...
    @property
    def on_error(self) -> Callable[[str, Any], Any] | None: ...
    @on_error.setter
    def on_error(self, cb: Callable[[str, Any], Any] | None) -> None: ...
    @property
    def on_open(self) -> Callable[[str, str], Any] | None: ...
    @on_open.setter
    def on_open(self, cb: Callable[[str, str], Any] | None) -> None: ...
    @property
    def on_close(self) -> Callable[[str], Any] | None: ...
    @on_close.setter
    def on_close(self, cb: Callable[[str], Any] | None) -> None: ...
    @property
    def on_stalled(self) -> Callable[[str, Any], Any] | None: ...
    @on_stalled.setter
    def on_stalled(self, cb: Callable[[str, Any], Any] | None) -> None: ...
    @property
    def on_shutdown(self) -> Callable[[], Any] | None: ...
    @on_shutdown.setter
    def on_shutdown(self, cb: Callable[[], Any] | None) -> None: ...
    @property
    def on_log(self) -> Callable[[str, int, str], Any] | None: ...
    @on_log.setter
    def on_log(self, cb: Callable[[str, int, str], Any] | None) -> None: ...
    def __init__(
        self,
        brokers: list[Credentials],
        candle_timeframes: list[tuple[int, bool, bool] | tuple[int, bool, bool, float]]
        | None = None,
        exchange_anchors: dict[str, int] = {
            "NSE": 13500,
            "BSE": 13500,
            "NFO": 13500,
            "BFO": 13500,
            "MCX": 12600,
            "CDS": 12600,
            "BCD": 12600,
        },
        timescale: TimescaleConfig | None = None,
        tick_queue_capacity: int = 100_000,
        tick_queue_overwrite: bool = True,
        candle_queue_capacity: int = 100_000,
        candle_queue_overwrite: bool = True,
    ) -> None: ...
    def start(
        self,
        on_tick: Callable[[Any], Any] | None = None,
        on_candle: Callable[[Any], Any] | None = None,
        on_order: Callable[[str, Any], Any] | None = None,
        on_error: Callable[[str, Any], Any] | None = None,
        on_open: Callable[[str, str], Any] | None = None,
        on_close: Callable[[str], Any] | None = None,
        on_stalled: Callable[[str, Any], Any] | None = None,
        on_shutdown: Callable[[], Any] | None = None,
        on_log: Callable[[str, int, str], Any] | None = None,
    ) -> None: ...
    def stop(self) -> None: ...
    def subscribe(
        self,
        instruments: list[str],
        feed_type: FeedType = FeedType.Touchline,
        target: str = "",
    ) -> None: ...
    def unsubscribe(
        self,
        instruments: list[str],
        feed_type: FeedType = FeedType.Touchline,
        target: str = "",
    ) -> None: ...
    def wait_connected(self, timeout: float | None = None) -> bool: ...
    def run(self, handle_signals: bool = True, grace_seconds: float = 2.0) -> None: ...
    @property
    def broker_count(self) -> int: ...
    @property
    def dropped_ticks(self) -> int: ...
    @property
    def dropped_candles(self) -> int: ...

class AsyncMergedFeed:
    on_tick: Callable[[Any], Any] | None
    on_order: Callable[[str, Any], Any] | None
    on_error: Callable[[str, Any], Any] | None
    on_open: Callable[[str, str], Any] | None
    on_close: Callable[[str], Any] | None
    on_stalled: Callable[[str, Any], Any] | None
    on_log: Callable[[str, int, str], Any] | None

    def __init__(
        self,
        brokers: list[Credentials],
        candle_timeframes: list[tuple[int, bool, bool] | tuple[int, bool, bool, float]]
        | None = None,
        exchange_anchors: dict[str, int] = {
            "NSE": 13500,
            "BSE": 13500,
            "NFO": 13500,
            "BFO": 13500,
            "MCX": 12600,
            "CDS": 12600,
            "BCD": 12600,
        },
        timescale: TimescaleConfig | None = None,
        tick_queue_capacity: int = 100_000,
        tick_queue_overwrite: bool = True,
        candle_queue_capacity: int = 100_000,
        candle_queue_overwrite: bool = True,
    ) -> None: ...
    async def start(
        self,
        on_tick: Callable[[Any], Any] | None = None,
        on_candle: Callable[[Any], Any] | None = None,
        on_order: Callable[[str, Any], Any] | None = None,
        on_error: Callable[[str, Any], Any] | None = None,
        on_open: Callable[[str, str], Any] | None = None,
        on_close: Callable[[str], Any] | None = None,
        on_stalled: Callable[[str, Any], Any] | None = None,
        on_log: Callable[[str, int, str], Any] | None = None,
    ) -> AsyncMergedFeed: ...
    async def subscribe(
        self,
        instruments: list[str],
        feed_type: FeedType = FeedType.Touchline,
        target: str = "",
    ) -> None: ...
    async def unsubscribe(
        self,
        instruments: list[str],
        feed_type: FeedType = FeedType.Touchline,
        target: str = "",
    ) -> None: ...
    async def wait_connected(self, timeout: float | None = None) -> bool: ...
    async def wait_closed(self) -> None: ...
    async def stop(self) -> None: ...
    async def aclose(self) -> None: ...
    async def __aenter__(self) -> AsyncMergedFeed: ...  # noqa: PYI034
    async def __aexit__(self, exc_type, exc, tb) -> bool: ...
    @property
    def broker_count(self) -> int: ...
